import type { Env as AppEnv } from '../src/types';

declare global {
  // The pool's `cloudflare:test` types read bindings from Cloudflare.Env
  // (normally generated by `wrangler types`); mirror our Env onto it.
  namespace Cloudflare {
    interface Env extends AppEnv {}
  }
}

declare module 'cloudflare:test' {
  interface ProvidedEnv extends AppEnv {}
}

export {};
